### ISSUE TITLE
IsADirectoryError: NeuralHash/

### ISSUE THREAD

**Issue by ioistired** [AsuharietYgvar/AppleNeuralHash2ONNX#5]
```
➤ ls NeuralHash/ -1
model.espresso.net
model.espresso.shape
model.espresso.weights
neuralhash_128x96_seed1.dat
NeuralHashv3b-current.espresso.net
NeuralHashv3b-current.espresso.shape
NeuralHashv3b-current.espresso.weights
(AppleNeuralHash2ONNX) ~/code/vcs/git/com/github/@/AsuharietYgvar/TNN|master⚡?
➤ python3 tools/onnx2tnn/onnx-coreml/onnx2coreml.py NeuralHash/
dir: NeuralHash
Traceback (most recent call last):
  File "/home/user/code/vcs/git/com/github/@/AsuharietYgvar/TNN/tools/onnx2tnn/onnx-coreml/onnx2coreml.py", line 60, in <module>
    main()
  File "/home/user/code/vcs/git/com/github/@/AsuharietYgvar/TNN/tools/onnx2tnn/onnx-coreml/onnx2coreml.py", line 32, in main
    onnx_model = onnx.load(onnx_net_path)
  File "/home/user/.local/share/venvs/home/user/code/vcs/git/com/github/@/AsuharietYgvar/AppleNeuralHash2ONNX/lib/python3.9/site-packages/onnx/__init__.py", line 120, in load_model
    s = _load_bytes(f)
  File "/home/user/.local/share/venvs/home/user/code/vcs/git/com/github/@/AsuharietYgvar/AppleNeuralHash2ONNX/lib/python3.9/site-packages/onnx/__init__.py", line 34, in _load_bytes
    with open(cast(Text, f), 'rb') as readable:
IsADirectoryError: [Errno 21] Is a directory: 'NeuralHash/'
```
What should I do?

**Comment by ioistired** [comment]
Wait, this is better suited to TNN. Closing to move it there.

**Comment by ioistired** [comment]
Nevermind, that repo has issues disabled…

**Comment by AsuharietYgvar** [comment]
You are running the wrong script. It's `coreml2onnx.py` not `onnx2coreml.py`.
