### ISSUE TITLE
Error when run "python3 tools/onnx2tnn/onnx-coreml/coreml2onnx.py ../NeuralHash_model"

### ISSUE THREAD

**Issue by testagain36** [AsuharietYgvar/AppleNeuralHash2ONNX#9]
I got the follow error when I run "python3 tools/onnx2tnn/onnx-coreml/coreml2onnx.py ../NeuralHash_model"
===========================
-> python3 tools/onnx2tnn/onnx-coreml/coreml2onnx.py ../NeuralHash_model
Traceback (most recent call last):
  File "tools/onnx2tnn/onnx-coreml/coreml2onnx.py", line 538, in <module>
    main()
  File "tools/onnx2tnn/onnx-coreml/coreml2onnx.py", line 35, in main
    net_layers = net_dict['layers']
KeyError: 'layers'
===========================
Could you please give some pointers how I can resolve it?

Thanks!

**Comment by testagain36** [comment]
Please ignore the issue.
